[build]
  functions = "netlify/functions"

[functions.auth]
  origin = "https://watchandearn.online"

[functions.save-wallet.js]
  origin = "https://watchandearn.online"

[functions.update-balance.js]
  origin = "https://watchandearn.online"

[functions.withdraw-notification.js]
  origin = "https://watchandearn.online"

[functions.watch-ad-reward.js]
  origin = "https://watchandearn.online"

[functions.activate-boost.js]
  origin = "https://watchandearn.online"

[functions.create-invoice.js]
  origin = "https://watchandearn.online"

[functions.verify-payment.js]
  origin = "https://watchandearn.online"

[functions.update-booster.js]
  origin = "https://watchandearn.online"