[build]
  functions = "netlify/functions"

[functions.auth]
  origin = "https://watchandearn.online"

[functions.save-wallet.js]
  origin = "https://watchandearn.online"

[functions.update-balance.js]
  origin = "https://watchandearn.online"

[functions.withdraw-notification.js]
  origin = "https://watchandearn.online"

[functions.user-notification.js]
  origin = "https://watchandearn.online"

[functions.watch-ad-reward.js]
  origin = "https://watchandearn.online"