[build]
  functions = "netlify/functions"

[functions.auth]
  origin = "https://cryptopayapp.netlify.app"

[functions.save-wallet.js]
  origin = "https://cryptopayapp.netlify.app"

[functions.update-balance.js]
  origin = "https://cryptopayapp.netlify.app"

[functions.withdraw-notification.js]
  origin = "https://cryptopayapp.netlify.app"